import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home(props) {
  console.log('main props', props);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href={'/csr'}>CSR</Link>
        <br />
        <Link href={'/ssr'}>SSR</Link>
        <br />
        <Link href={'/ssg'}>SSG</Link>
      </main>
    </div>
  );
}
